apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx # label of your pod
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80 # internal port used by container
      nodePort: 30007  # This port can be any valid port within the NodePort range
  type: NodePort